Am pm
TimberTracks/clockpicker pull request #1
Opened 2019-04-04 18:21 UTC by znotdead

2019-04-05 19:26 UTC, Rj7 requested changes

2019-04-05 19:26 UTC, Rj7 commented on index.html
> +  twelvehour: true,
formatting.

2019-04-05 19:26 UTC, Rj7 commented on src/clockpicker.js
> +    var last = this.input.prop('value'), value;
```suggestion
    var last = this.input.prop('value');
```
is that a typo?

2019-04-05 21:07 UTC, znotdead commented on src/clockpicker.js
> +    var last = this.input.prop('value'), value;
it's not a typo. it's short for:
```
var last = this.....;
var value;
```

2019-04-08 15:36 UTC, Rj7 approved these changes

2019-04-08 15:36 UTC, Rj7 approved these changes

2019-04-08 15:37 UTC, Rj7 commented on src/clockpicker.js
> +    var last = this.input.prop('value'), value;
just making sure that what you meant.

2019-04-08 15:37 UTC, Rj7 commented
@znotdead I need write access to merge.

2019-04-08 16:21 UTC, znotdead commented
> @znotdead I need write access to merge.

Done

2019-04-08 16:35 UTC, merged